moustache:
    resource: "@MoustacheBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_check:
    path: /chklogin
    defaults: { _controller: FOSUserBundle:Security:check }
