moustache_torrent:
    path: /
    defaults: { _controller: moustache.controller.default:listAction }
    methods:  [GET]

moustache_torrent_content:
    path: /content/{id}
    defaults: { _controller: moustache.controller.default:torrentContentAction  }
    requirements:
        id: \d+
    methods:  [GET]

moustache_torrent_add:
    path: /add
    defaults: { _controller: moustache.controller.add:addAction  }
    methods:  [POST]

moustache_torrent_download:
    path: /ddl/{id}
    defaults: { _controller: moustache.controller.download:downloadAction  }
    methods:  [POST,GET]

moustache_torrent_remove:
    path: /remove/{id}
    defaults: { _controller: moustache.controller.remove:removeAction  }
    requirements:
        id: \d+
    methods:  [POST,GET]

moustache_torrent_stop:
    path: /stop/{id}
    defaults: { _controller: moustache.controller.life_cycle:stopAction  }
    requirements:
        id: \d+
    methods:  [POST,GET]

moustache_torrent_start:
    path: /start/{id}
    defaults: { _controller: moustache.controller.life_cycle:startAction  }
    requirements:
        id: \d+
    methods:  [POST,GET]

moustache_signup_form:
    path: /signup/form/{confirmationToken}
    defaults: { _controller: moustache.controller.signup:formAction }
    requirements:
        confirmationToken: "[a-f0-9]+"
    methods:  [GET]

moustache_signup_signup:
    path: /signup/{confirmationToken}
    defaults: { _controller: moustache.controller.signup:signupAction }
    requirements:
        confirmationToken: "[a-f0-9]+"
    methods:  [POST]

moustache_status_get:
    path: /status/{id}
    defaults: { _controller: moustache.controller.status:getAction }
    requirements:
        id: \d+
    methods:  [GET]

moustache_status_getAll:
    path: /status
    defaults: { _controller: moustache.controller.status:getAllAction }
    methods:  [GET]
