services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    # --- Command
    moustache.command.generate_signup:
        class: "MoustacheBundle\\Command\\GenerateSignupCommand"
        arguments:
            - "@torrent.repository.user"
            - "@torrent.manager.user"
            - "@router"
        tags:
            - { name: console.command }
    moustache.command.install:
        class: "MoustacheBundle\\Command\\InstallCommand"
        arguments:
            - "@moustache.task.symlink_parameters"
        tags:
            - { name: console.command }

    # --- Controllers
    moustache.controller.add:
        class: "MoustacheBundle\\Controller\\AddController"
        arguments:
            - "@moustache.form.torrent_menu"
            - "@torrent.client.current"
            - "@torrent.manager.torrent"
            - "@moustache.service.redirector"
            - "@request_stack"
            - "@logger"
            - "%torrent_rpc_client%"
    moustache.controller.default:
        class: "MoustacheBundle\\Controller\\DefaultController"
        arguments:
            - "@torrent.client.current"
            - "@templating"
            - "@moustache.form.torrent_menu"
    moustache.controller.download:
        class: "MoustacheBundle\\Controller\\DownloadController"
        arguments:
            - "@torrent.client.current"
            - "@moustache.service.torrent_publisher"
            - "@moustache.service.redirector"
    moustache.controller.life_cycle:
        class: "MoustacheBundle\\Controller\\LifeCycleController"
        arguments:
            - "@torrent.client.current"
            - "@moustache.service.redirector"
    moustache.controller.remove:
        class: "MoustacheBundle\\Controller\\RemoveController"
        arguments:
            - "@torrent.client.current"
            - "@moustache.service.redirector"
    moustache.controller.signup:
        class: "MoustacheBundle\\Controller\\SignupController"
        arguments:
            - "@templating"
            - "@torrent.manager.user"
            - "@torrent.repository.user"
            - "@moustache.form.signup"
            - "@fos_user.security.login_manager"
            - "@moustache.service.redirector"
            - "@moustache.shortcut.request"
    moustache.controller.status:
        class: "MoustacheBundle\\Controller\\StatusController"
        arguments:
            - "@torrent.client.current"

    # --- Event Listeners
    moustache.event_listener.cache_outdated_redirector:
        class: "MoustacheBundle\\EventListener\\CacheOutdatedRedirectorListener"
        arguments:
            - "@moustache.service.redirector"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -50 }
    moustache.event_listener.flash_bag_messenger:
        class: "MoustacheBundle\\EventListener\\FlashBagMessengerListener"
        arguments:
            - "@moustache.helper.flash_bag"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 1 }
    moustache.event_listener.maintenance:
        class: "MoustacheBundle\\EventListener\\MaintenanceListener"
        arguments:
            - "%maintenance_lock_file%"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 2000}
    moustache.event_listener.missing_torrent_warner:
        class: "MoustacheBundle\\EventListener\\MissingTorrentWarnerListener"
        arguments:
            - "@logger"
            - "@moustache.helper.flash_bag"
            - "@torrent.client.current"
            - "@request_stack"
        tags:
            - { name: kernel.event_listener, event: moustache.torrent.missing, method: onTorrentMissing, priority: 0}
    moustache.event_listener.locale_setter:
        class: "MoustacheBundle\\EventListener\\LocaleSetterListener"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200}

    # --- Helper
    moustache.helper.flash_bag:
        class: "MoustacheBundle\\Helper\\FlashBagHelper"
        arguments:
            - "@moustache.service.flash_messager"
            - "@torrent.helper.authenticated_user"
            - "@torrent.manager.user"

    # --- Forms
    moustache.form.torrent_menu:
        class: "MoustacheBundle\\Form\\TorrentMenu"
        factory: 'form.factory:create'
        arguments:
            - "MoustacheBundle\\Form\\TorrentMenu"
            - "@torrent.entity.torrent"
    moustache.form.signup:
        class: "MoustacheBundle\\Form\\Signup"
        factory: 'form.factory:create'
        arguments:
            - "MoustacheBundle\\Form\\Signup"

    # --- Services
    moustache.service.flash_messager:
        class: "MoustacheBundle\\Service\\FlashMessenger"
        arguments:
            - "@session"
            - "@translator"
    moustache.service.torrent_link_generator:
        class: "MoustacheBundle\\Service\\TorrentLinkGenerator"
        arguments:
            - "@session"
            - "@router"
            - "%kernel.root_dir%"
    moustache.service.torrent_publisher:
        class: "MoustacheBundle\\Service\\TorrentPublisher"
        arguments:
            - "@filesystem"
            - "@moustache.service.torrent_link_generator"
            - "%allow_direct_download%"
    moustache.service.redirector:
        class: "MoustacheBundle\\Service\\Redirector"
        arguments:
            - "@router"
            - "@moustache.service.flash_messager"

    # --- Shortcut
    moustache.shortcut.request:
        class: "Symfony\\Component\\HttpFoundation\\Request"
        factory: 'request_stack:getCurrentRequest'

    # --- Tasks
    moustache.task.symlink_parameters:
        class: "MoustacheBundle\\Task\\SymlinkParametersTask"
        arguments:
            - "@filesystem"
            - "%kernel.root_dir%"
            - "%system_conf_dir%"

    # --- Twig
    moustache.twig.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
